#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Surtr.Interop.SourceGenerator
{
    /// <summary>
    /// Emits, at compile time, the shims and registration code that link a
    /// <c>[SurtrNativeType]</c> CLR type to Surtr, plus the <c>SurtrBindings</c> catalog. Emits a
    /// partial part into <c>partial</c> types and a separate helper class for non-partial ones.
    /// </summary>
    [Generator]
    public sealed class SurtrSourceGenerator : ISourceGenerator
    {
        private const string GeneratedCodeAttribute =
            "[System.CodeDom.Compiler.GeneratedCode(\"Surtr.Interop.SourceGenerator\", \"1.0.0\")]";

        public void Initialize(GeneratorInitializationContext context)
            => context.RegisterForSyntaxNotifications(() => new SurtrSyntaxReceiver());

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not SurtrSyntaxReceiver receiver || receiver.Candidates.Count == 0)
                return;

            var compilation = context.Compilation;
            var typeSymbols = new List<INamedTypeSymbol>();

            foreach (var candidate in receiver.Candidates)
            {
                var model = compilation.GetSemanticModel(candidate.SyntaxTree);
                if (model.GetDeclaredSymbol(candidate, context.CancellationToken) is not INamedTypeSymbol symbol)
                    continue;

                if (GeneratorSupport.FindAttribute(symbol, GeneratorSupport.NativeTypeAttribute) is not null)
                    typeSymbols.Add(symbol);
            }

            if (typeSymbols.Count == 0)
                return;

            var builder = new StringBuilder();

            foreach (var type in typeSymbols)
            {
                var source = EmitType(type);
                builder.AppendLine(source);

                var hint = "SurtrGenerated." + Sanitize(type.ToDisplayString()) + ".g.cs";
                context.AddSource(hint, SourceText.From(source, Encoding.UTF8));
            }

            context.AddSource("SurtrGenerated.Bindings.g.cs", SourceText.From(EmitBindings(typeSymbols), Encoding.UTF8));
        }

        private static string EmitBindings(List<INamedTypeSymbol> types)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using Surtr.Runtime;");
            builder.AppendLine("using Surtr.Runtime.Classes;");
            builder.AppendLine();
            builder.AppendLine("namespace Surtr.Interop");
            builder.AppendLine("{");
            builder.AppendLine("    public static class SurtrBindings");
            builder.AppendLine("    {");
            builder.AppendLine("        " + GeneratedCodeAttribute);
            builder.AppendLine("        public static void RegisterAll(SurtrRuntime runtime)");
            builder.AppendLine("        {");

            foreach (var type in types)
            {
                string accessor = RegistrationAccessor(type);
                builder.AppendLine("            " + accessor + ".__SurtrRegister(runtime);");
            }

            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static string EmitType(INamedTypeSymbol type)
        {
            var attribute = GeneratorSupport.FindAttribute(type, GeneratorSupport.NativeTypeAttribute)!;
            int policy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? GeneratorSupport.PolicyDefault;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name")
                ?? GeneratorSupport.Apply(type.Name, policy, isMember: false);
            string? module = GeneratorSupport.GetStringNamed(attribute, "Module");
            string fullName = module is null ? name : module + ":" + name;

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using Surtr.Runtime;");
            builder.AppendLine("using Surtr.Runtime.Classes;");
            builder.AppendLine("using Surtr.Runtime.Objects;");
            builder.AppendLine("using Surtr.Interop;");
            builder.AppendLine();

            string ns = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();

            if (!string.IsNullOrEmpty(ns))
            {
                builder.AppendLine("namespace " + ns);
                builder.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(ns) ? string.Empty : "    ";
            bool isPartial = type.DeclaringSyntaxReferences.Any(static r => r.GetSyntax() is TypeDeclarationSyntax { } t && t.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)));

            if (type.TypeKind == TypeKind.Enum)
            {
                EmitEnumRegistration(builder, type, attribute, name, module, fullName, indent);
            }
            else if (isPartial)
            {
                builder.AppendLine(indent + "public partial class " + type.Name);
                builder.AppendLine(indent + "{");
                EmitMembers(builder, type, policy, indent + "    ");
                builder.AppendLine(indent + "}");
            }
            else
            {
                builder.AppendLine(indent + "internal static class SurtrGenerated_" + type.Name);
                builder.AppendLine(indent + "{");
                EmitMembers(builder, type, policy, indent + "    ");
                builder.AppendLine(indent + "}");
            }

            if (!string.IsNullOrEmpty(ns))
                builder.AppendLine("}");

            return builder.ToString();
        }

        private static void EmitEnumRegistration(StringBuilder builder, INamedTypeSymbol type, AttributeData attribute, string name, string? module, string fullName, string indent)
        {
            string enumType = type.ToDisplayString();
            var fields = type.GetMembers().OfType<IFieldSymbol>().Where(static f => f.HasConstantValue).ToList();

            builder.AppendLine(indent + "internal static class SurtrGenerated_" + type.Name);
            builder.AppendLine(indent + "{");
            builder.AppendLine(indent + "    " + GeneratedCodeAttribute);
            builder.AppendLine(indent + "    internal static SurtrClass __SurtrRegister(SurtrRuntime runtime)");
            builder.AppendLine(indent + "    {");
            builder.AppendLine(indent + "        var d = new NativeTypeDescriptor");
            builder.AppendLine(indent + "        {");
            builder.AppendLine(indent + "            FullName = \"" + fullName + "\",");
            builder.AppendLine(indent + "            Name = \"" + name + "\",");
            builder.AppendLine(indent + "            Kind = NativeTypeKind.Enum,");
            builder.AppendLine(indent + "            EnumCases = new string[] { " + string.Join(", ", fields.Select(f => "\"" + f.Name + "\"")) + " },");
            builder.AppendLine(indent + "            EnumValues = new object[] { " + string.Join(", ", fields.Select(f => "(object)" + enumType + "." + f.Name)) + " },");
            builder.AppendLine(indent + "        };");
            builder.AppendLine(indent + "        return SurtrBridge.Register(runtime, d);");
            builder.AppendLine(indent + "    }");
            builder.AppendLine(indent + "}");
        }

        private static void EmitMembers(StringBuilder builder, INamedTypeSymbol type, int policy, string indent)
        {
            var methods = new List<IMethodSymbol>();
            var fields = new List<IFieldSymbol>();
            var properties = new List<IPropertySymbol>();

            foreach (var constructor in type.InstanceConstructors.Where(static c => c.DeclaredAccessibility == Accessibility.Public && !c.IsStatic))
                methods.Add(constructor);

            foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
            {
                if (method.MethodKind == MethodKind.Ordinary
                    && method.DeclaredAccessibility == Accessibility.Public
                    && GeneratorSupport.FindAttribute(method, GeneratorSupport.NativeIgnoreAttribute) is null
                    && (GeneratorSupport.FindAttribute(method, GeneratorSupport.NativeMethodAttribute) is { } m && !IsExposeFalse(m) ? true : true))
                {
                    methods.Add(method);
                }
            }

            foreach (var field in type.GetMembers().OfType<IFieldSymbol>())
            {
                if (field.DeclaredAccessibility == Accessibility.Public
                    && !field.IsConst
                    && !field.IsImplicitlyDeclared
                    && GeneratorSupport.FindAttribute(field, GeneratorSupport.NativeIgnoreAttribute) is null)
                {
                    fields.Add(field);
                }
            }

            foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
            {
                if (property.DeclaredAccessibility == Accessibility.Public
                    && !property.IsIndexer
                    && GeneratorSupport.FindAttribute(property, GeneratorSupport.NativeIgnoreAttribute) is null)
                {
                    properties.Add(property);
                }
            }

            var descriptors = new List<string>();

            foreach (var method in methods)
                descriptors.Add(EmitMethod(builder, type, method, policy, indent));

            foreach (var field in fields)
                descriptors.Add(EmitField(builder, type, field, policy, indent));

            foreach (var property in properties)
                descriptors.Add(EmitProperty(builder, type, property, policy, indent));

            EmitRegistration(builder, type, policy, descriptors, indent);
        }

        private static string EmitMethod(StringBuilder builder, INamedTypeSymbol type, IMethodSymbol method, int policy, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(method, GeneratorSupport.NativeMethodAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = method.MethodKind == MethodKind.Constructor
                ? "ctor"
                : GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(method.Name, memberPolicy, isMember: true);

            string shimName = "__SurtrInvoke_" + type.Name + "_" + (method.MethodKind == MethodKind.Constructor ? "ctor" : method.Name) + "_" + method.Parameters.Length;
            EmitMethodShim(builder, type, method, shimName, indent);

            var parameters = new List<string>();
            int argIndex = method.IsStatic ? 0 : 1;
            foreach (var parameter in method.Parameters)
            {
                if (parameter.RefKind == RefKind.Out || parameter.RefKind == RefKind.Ref)
                    continue;

                string paramName = GeneratorSupport.GetStringNamed(
                    GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute),
                    "Name") ?? GeneratorSupport.Apply(parameter.Name, memberPolicy, isMember: true);

                string paramDescriptor = GeneratorSupport.GetStringNamed(
                    GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute),
                    "TypeDescriptor") ?? GeneratorSupport.MapType(parameter.Type);

                parameters.Add("new NativeParameterDescriptor { Name = \"" + paramName + "\", TypeDescriptor = \"" + paramDescriptor + "\" }");
            }

            string returnDescriptor = BuildReturnDescriptor(method, attribute, memberPolicy);

            var descriptor = new StringBuilder();
            descriptor.Append("new NativeMethodDescriptor { Name = \"" + name + "\"");
            descriptor.Append(", IsStatic = " + (method.IsStatic ? "true" : "false"));
            descriptor.Append(", IsConstructor = " + (method.MethodKind == MethodKind.Constructor ? "true" : "false"));
            descriptor.Append(", ReturnDescriptor = \"" + returnDescriptor + "\"");
            descriptor.Append(", Parameters = new NativeParameterDescriptor[] { " + string.Join(", ", parameters) + " }");
            descriptor.Append(", EntryPoint = SurtrNativeEntryPoint.FromFunctionPointer(&" + shimName + ")");
            descriptor.Append(" }");

            return descriptor.ToString();
        }

        private static void EmitMethodShim(StringBuilder builder, INamedTypeSymbol type, IMethodSymbol method, string shimName, string indent)
        {
            string typeName = type.ToDisplayString();

            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "private static SurtrValue " + shimName + "(SurtrCallArguments args)");
            builder.AppendLine(indent + "{");

            string targetExpr;
            if (method.IsStatic)
                targetExpr = typeName;
            else
            {
                builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                targetExpr = "__target";
            }

            var arguments = new List<string>();
            int argIndex = method.IsStatic ? 0 : 1;

            foreach (var parameter in method.Parameters)
            {
                if (parameter.RefKind == RefKind.Ref)
                    continue;

                if (parameter.RefKind == RefKind.Out)
                {
                    builder.AppendLine(indent + "    " + OutDeclaration(parameter));
                    arguments.Add("out " + parameter.Name);
                    continue;
                }

                string clr = ToClrExpression(parameter.Type, argIndex);
                builder.AppendLine(indent + "    var " + parameter.Name + " = " + clr + ";");
                arguments.Add(parameter.Name);
                argIndex++;
            }

            string returnExpr;
            if (method.MethodKind == MethodKind.Constructor)
                returnExpr = "SurtrValue.CreateReference(args.Runtime.WrapNative(new " + typeName + "(" + string.Join(", ", arguments) + ")).GetSurtrReference())";
            else if (method.ReturnsVoid)
                returnExpr = "SurtrValue.Null";
            else
                returnExpr = ToSurtrExpression(method.ReturnType, targetExpr + "." + method.Name + "(" + string.Join(", ", arguments) + ")");

            bool hasOut = method.Parameters.Any(static p => p.RefKind == RefKind.Out);
            if (!hasOut)
            {
                builder.AppendLine(indent + "    return " + returnExpr + ";");
            }
            else
            {
                EmitOutReturn(builder, method, targetExpr, arguments, indent);
            }

            builder.AppendLine(indent + "}");
            builder.AppendLine();
        }

        private static void EmitOutReturn(StringBuilder builder, IMethodSymbol method, string targetExpr, List<string> arguments, string indent)
        {
            string call = method.MethodKind == MethodKind.Constructor
                ? "new " + method.ContainingType.ToDisplayString() + "(" + string.Join(", ", arguments) + ")"
                : targetExpr + "." + method.Name + "(" + string.Join(", ", arguments) + ")";

            builder.AppendLine(indent + "    var __result = " + call + ";");

            var outParams = method.Parameters.Where(static p => p.RefKind == RefKind.Out).ToList();

            if (outParams.Count == 1 && method.ReturnsVoid)
            {
                builder.AppendLine(indent + "    return " + ToSurtrExpression(outParams[0].Type, outParams[0].Name) + ";");
                return;
            }

            var elements = new List<string>();
            if (!method.ReturnsVoid)
                elements.Add(ToSurtrExpression(method.ReturnType, "__result"));
            foreach (var p in outParams)
                elements.Add(ToSurtrExpression(p.Type, p.Name));

            var tupleDescriptor = BuildTupleDescriptor(method);
            builder.AppendLine(indent + "    var __tuple = args.Runtime.NewTuple(SurtrClassReference.FromDescriptor(\"" + tupleDescriptor + "\"), new SurtrValue[] { " + string.Join(", ", elements) + " });");
            builder.AppendLine(indent + "    return SurtrValue.CreateReference(__tuple.GetSurtrReference());");
        }

        private static string EmitField(StringBuilder builder, INamedTypeSymbol type, IFieldSymbol field, int policy, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(field, GeneratorSupport.NativeFieldAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(field.Name, memberPolicy, isMember: true);
            string typeDescriptor = GeneratorSupport.GetStringNamed(attribute, "TypeDescriptor") ?? GeneratorSupport.MapType(field.Type);
            bool readOnly = field.IsReadOnly || field.IsConst || GeneratorSupport.GetIntNamed(attribute, "ReadOnly") == 1;

            string typeName = type.ToDisplayString();
            string getterShim = "__SurtrFieldGet_" + type.Name + "_" + field.Name;
            string setterShim = "__SurtrFieldSet_" + type.Name + "_" + field.Name;

            // Getter shim.
            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "private static SurtrValue " + getterShim + "(SurtrCallArguments args)");
            builder.AppendLine(indent + "{");
            string target = field.IsStatic
                ? typeName
                : "args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!";
            if (!field.IsStatic)
                builder.AppendLine(indent + "    var __target = " + target + ";");
            builder.AppendLine(indent + "    return " + ToSurtrExpression(field.Type, (field.IsStatic ? typeName : "__target") + "." + field.Name) + ";");
            builder.AppendLine(indent + "}");
            builder.AppendLine();

            // Setter shim (unless read-only).
            if (!readOnly)
            {
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static SurtrValue " + setterShim + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                if (!field.IsStatic)
                    builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                int valueIndex = field.IsStatic ? 0 : 1;
                builder.AppendLine(indent + "    var __value = " + ToClrExpression(field.Type, valueIndex) + ";");
                builder.AppendLine(indent + "    " + (field.IsStatic ? typeName : "__target") + "." + field.Name + " = __value;");
                builder.AppendLine(indent + "    return SurtrValue.Null;");
                builder.AppendLine(indent + "}");
                builder.AppendLine();
            }

            return "new NativeFieldDescriptor { Name = \"" + name + "\", IsStatic = " + (field.IsStatic ? "true" : "false") + ", ReadOnly = " + (readOnly ? "true" : "false") + ", TypeDescriptor = \"" + typeDescriptor + "\", Getter = SurtrNativeEntryPoint.FromFunctionPointer(&" + getterShim + "), Setter = " + (readOnly ? "default" : "SurtrNativeEntryPoint.FromFunctionPointer(&" + setterShim + ")") + " }";
        }

        private static string EmitProperty(StringBuilder builder, INamedTypeSymbol type, IPropertySymbol property, int policy, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(property, GeneratorSupport.NativePropertyAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(property.Name, memberPolicy, isMember: true);
            string typeDescriptor = GeneratorSupport.GetStringNamed(attribute, "TypeDescriptor") ?? GeneratorSupport.MapType(property.Type);

            string typeName = type.ToDisplayString();
            bool hasGetter = property.GetMethod is { DeclaredAccessibility: Accessibility.Public };
            bool hasSetter = property.SetMethod is { DeclaredAccessibility: Accessibility.Public };
            bool isStatic = (property.GetMethod ?? property.SetMethod)?.IsStatic ?? false;

            string getterShim = "__SurtrPropGet_" + type.Name + "_" + property.Name;
            string setterShim = "__SurtrPropSet_" + type.Name + "_" + property.Name;

            if (hasGetter)
            {
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static SurtrValue " + getterShim + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                string target = isStatic ? typeName : "args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!";
                if (!isStatic)
                    builder.AppendLine(indent + "    var __target = " + target + ";");
                builder.AppendLine(indent + "    return " + ToSurtrExpression(property.Type, (isStatic ? typeName : "__target") + "." + property.Name) + ";");
                builder.AppendLine(indent + "}");
                builder.AppendLine();
            }

            if (hasSetter)
            {
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static SurtrValue " + setterShim + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                if (!isStatic)
                    builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                int valueIndex = isStatic ? 0 : 1;
                builder.AppendLine(indent + "    var __value = " + ToClrExpression(property.Type, valueIndex) + ";");
                builder.AppendLine(indent + "    " + (isStatic ? typeName : "__target") + "." + property.Name + " = __value;");
                builder.AppendLine(indent + "    return SurtrValue.Null;");
                builder.AppendLine(indent + "}");
                builder.AppendLine();
            }

            return "new NativePropertyDescriptor { Name = \"" + name + "\", IsStatic = " + (isStatic ? "true" : "false") + ", HasGetter = " + (hasGetter ? "true" : "false") + ", HasSetter = " + (hasSetter ? "true" : "false") + ", TypeDescriptor = \"" + typeDescriptor + "\", Getter = " + (hasGetter ? "SurtrNativeEntryPoint.FromFunctionPointer(&" + getterShim + ")" : "default") + ", Setter = " + (hasSetter ? "SurtrNativeEntryPoint.FromFunctionPointer(&" + setterShim + ")" : "default") + " }";
        }

        private static void EmitRegistration(StringBuilder builder, INamedTypeSymbol type, int policy, List<string> descriptors, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(type, GeneratorSupport.NativeTypeAttribute)!;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(type.Name, policy, isMember: false);
            string? module = GeneratorSupport.GetStringNamed(attribute, "Module");
            string fullName = module is null ? name : module + ":" + name;
            string kind = type.TypeKind == TypeKind.Struct ? "NativeTypeKind.Struct" : "NativeTypeKind.Class";

            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "internal static unsafe SurtrClass __SurtrRegister(SurtrRuntime runtime)");
            builder.AppendLine(indent + "{");
            builder.AppendLine(indent + "    var d = new NativeTypeDescriptor");
            builder.AppendLine(indent + "    {");
            builder.AppendLine(indent + "        FullName = \"" + fullName + "\",");
            builder.AppendLine(indent + "        Name = \"" + name + "\",");
            builder.AppendLine(indent + "        Kind = " + kind + ",");
            builder.AppendLine(indent + "        Members = new NativeMemberDescriptor[] { " + string.Join(", ", descriptors) + " },");
            builder.AppendLine(indent + "    };");
            builder.AppendLine(indent + "    return SurtrBridge.Register(runtime, d);");
            builder.AppendLine(indent + "}");
        }

        private static string RegistrationAccessor(INamedTypeSymbol type)
        {
            bool isPartial = type.DeclaringSyntaxReferences.Any(static r => r.GetSyntax() is TypeDeclarationSyntax { } t && t.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)));
            if (type.TypeKind == TypeKind.Enum || !isPartial)
                return "global::" + type.ContainingNamespace.ToDisplayString() + ".SurtrGenerated_" + type.Name;
            return "global::" + type.ToDisplayString();
        }

        private static string BuildReturnDescriptor(IMethodSymbol method, AttributeData? attribute, int policy)
        {
            var outParams = method.Parameters.Where(static p => p.RefKind == RefKind.Out).ToList();
            string declared = GeneratorSupport.GetStringNamed(attribute, "ReturnDescriptor") ?? string.Empty;

            if (outParams.Count == 0)
                return declared.Length > 0 ? declared : GeneratorSupport.MapType(method.ReturnType);

            string? returnRef = method.ReturnsVoid ? null : (declared.Length > 0 ? declared : GeneratorSupport.MapType(method.ReturnType));

            if (outParams.Count == 1 && method.ReturnsVoid)
                return GeneratorSupport.MapType(outParams[0].Type);

            var elements = new List<string>();
            if (returnRef is not null)
                elements.Add(returnRef);
            foreach (var p in outParams)
                elements.Add(GeneratorSupport.MapType(p.Type));

            return "T(" + string.Join("", elements) + ")";
        }

        private static string BuildTupleDescriptor(IMethodSymbol method)
        {
            var elements = new List<string>();
            if (!method.ReturnsVoid)
                elements.Add(GeneratorSupport.MapType(method.ReturnType));
            foreach (var p in method.Parameters.Where(static p => p.RefKind == RefKind.Out))
                elements.Add(GeneratorSupport.MapType(p.Type));

            return "T(" + string.Join("", elements) + ")";
        }

        private static string OutDeclaration(IParameterSymbol parameter)
            => parameter.Type.ToDisplayString() + " " + parameter.Name;

        private static string ToClrExpression(ITypeSymbol type, int index)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_SByte: return "(sbyte)args.GetInt(" + index + ")";
                case SpecialType.System_Byte: return "(byte)args.GetInt(" + index + ")";
                case SpecialType.System_Int16: return "(short)args.GetInt(" + index + ")";
                case SpecialType.System_UInt16: return "(ushort)args.GetInt(" + index + ")";
                case SpecialType.System_Int32: return "args.GetInt(" + index + ")";
                case SpecialType.System_UInt32: return "(uint)args.GetInt(" + index + ")";
                case SpecialType.System_Int64: return "args.GetInt(" + index + ")";
                case SpecialType.System_UInt64: return "(ulong)args.GetInt(" + index + ")";
                case SpecialType.System_Single: return "(float)args.GetFloat(" + index + ")";
                case SpecialType.System_Double: return "args.GetFloat(" + index + ")";
                case SpecialType.System_Decimal: return "(decimal)args.GetFloat(" + index + ")";
                case SpecialType.System_Boolean: return "args.GetBool(" + index + ")";
                case SpecialType.System_Char: return "args.GetChar(" + index + ")";
                case SpecialType.System_String: return "args.GetString(" + index + ").Text";
                case SpecialType.System_Object: return "args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(" + index + "))!.Target";
            }

            if (type.TypeKind == TypeKind.Enum)
                return "SurtrEnums.ToClr<" + type.ToDisplayString() + ">(args.Runtime, args.GetValue(" + index + "))";

            return "args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(" + index + "))!.TargetAs<" + type.ToDisplayString() + ">()!";
        }

        private static string ToSurtrExpression(ITypeSymbol type, string expression)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_SByte:
                case SpecialType.System_Byte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                    return "SurtrValue.CreateInt((int)(" + expression + "))";

                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_Decimal:
                    return "SurtrValue.CreateFloat((double)(" + expression + "))";

                case SpecialType.System_Boolean:
                    return "SurtrValue.CreateBool(" + expression + ")";

                case SpecialType.System_Char:
                    return "SurtrValue.CreateChar(" + expression + ")";

                case SpecialType.System_String:
                    return "SurtrValue.CreateReference(args.Runtime.InternString(" + expression + ").GetSurtrReference())";

                case SpecialType.System_Object:
                    return "SurtrValue.CreateReference(args.Runtime.WrapNative(" + expression + ").GetSurtrReference())";
            }

            if (type.TypeKind == TypeKind.Enum)
                return "SurtrEnums.ToSurtr(args.Runtime, " + expression + ")";

            return "SurtrValue.CreateReference(args.Runtime.WrapNative(" + expression + ").GetSurtrReference())";
        }

        private static bool IsExposeFalse(AttributeData attribute)
        {
            foreach (var pair in attribute.NamedArguments)
            {
                if (pair.Key == "Expose" && pair.Value.Value is false)
                    return true;
            }

            return false;
        }

        private static string Sanitize(string name)
        {
            var builder = new StringBuilder(name.Length);
            foreach (char c in name)
                builder.Append(char.IsLetterOrDigit(c) ? c : '_');
            return builder.ToString();
        }

        private sealed class SurtrSyntaxReceiver : ISyntaxReceiver
        {
            internal readonly List<TypeDeclarationSyntax> Candidates = new();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 } type)
                    Candidates.Add(type);
            }
        }
    }
}
