#nullable enable

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Surtr.Interop.SourceGenerator
{
    /// <summary>
    /// Emits, at compile time, the shims and registration code that link a
    /// <c>[SurtrNativeType]</c> CLR type to Surtr, plus the <c>SurtrBindings</c> catalog. Emits a
    /// partial part into <c>partial</c> types and a separate helper class for non-partial ones.
    /// </summary>
    [Generator]
    public sealed class SurtrSourceGenerator : ISourceGenerator
    {
        private const string GeneratedCodeAttribute =
            "[System.CodeDom.Compiler.GeneratedCode(\"Surtr.Interop.SourceGenerator\", \"1.0.0\")]";

        public void Initialize(GeneratorInitializationContext context)
            => context.RegisterForSyntaxNotifications(() => new SurtrSyntaxReceiver());

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.SyntaxReceiver is not SurtrSyntaxReceiver receiver || receiver.Candidates.Count == 0)
                return;

            var compilation = context.Compilation;
            var attributed = new List<INamedTypeSymbol>();

            foreach (var candidate in receiver.Candidates)
            {
                var model = compilation.GetSemanticModel(candidate.SyntaxTree);
                if (model.GetDeclaredSymbol(candidate, context.CancellationToken) is not INamedTypeSymbol symbol)
                    continue;

                if (GeneratorSupport.FindAttribute(symbol, GeneratorSupport.NativeTypeAttribute) is not null)
                    attributed.Add(symbol);
            }

            if (attributed.Count == 0)
                return;

            // Expand closed generic forms and report unsupported members as warnings.
            var typeSymbols = new List<INamedTypeSymbol>();
            foreach (var type in attributed)
            {
                foreach (var expanded in ExpandClosedForms(type, context))
                    typeSymbols.Add(expanded);

                ValidateType(context, type);
                ReportWarnings(context, type);
            }

            context.AddSource("SurtrGenerated.Bindings.g.cs", SourceText.From(EmitBindings(typeSymbols), Encoding.UTF8));

            foreach (var type in typeSymbols)
            {
                var source = EmitType(type);
                var hint = "SurtrGenerated." + Sanitize(type.ToDisplayString()) + ".g.cs";
                context.AddSource(hint, SourceText.From(source, Encoding.UTF8));
            }
        }

        /// <summary>
        /// Yields the type symbols to emit: a non-generic type as itself, a generic type once per
        /// closed form named in its <c>TypeArguments</c>. An open generic with no closed form is
        /// skipped with a warning.
        /// </summary>
        private static IEnumerable<INamedTypeSymbol> ExpandClosedForms(INamedTypeSymbol type, GeneratorExecutionContext context)
        {
            if (!type.IsGenericType)
            {
                yield return type;
                yield break;
            }

            var attribute = GeneratorSupport.FindAttribute(type, GeneratorSupport.NativeTypeAttribute)!;
            var typeArguments = ReadTypeArguments(attribute);

            if (typeArguments.Count == 0)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    SurtrDiagnostics.UnsupportedMember,
                    type.Locations.FirstOrDefault(),
                    type.Name,
                    type.ContainingNamespace.ToDisplayString(),
                    "open generic types are not exposed; add TypeArguments for each closed form"));

                yield break;
            }

            if (typeArguments.Count != type.Arity)
            {
                // Reported as an error by ValidateType; just do not construct the broken form.
                yield break;
            }

            yield return type.Construct(typeArguments.ToArray());
        }

        private static string EmitBindings(List<INamedTypeSymbol> types)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using Surtr.Runtime;");
            builder.AppendLine("using Surtr.Runtime.Classes;");
            builder.AppendLine();
            builder.AppendLine("namespace Surtr.Interop");
            builder.AppendLine("{");
            builder.AppendLine("    public static class SurtrBindings");
            builder.AppendLine("    {");
            builder.AppendLine("        " + GeneratedCodeAttribute);
            builder.AppendLine("        public static void RegisterAll(SurtrRuntime runtime)");
            builder.AppendLine("        {");

            foreach (var type in types)
            {
                string accessor = RegistrationAccessor(type);
                builder.AppendLine("            " + accessor + ".__SurtrRegister(runtime);");
            }

            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }

        private static string EmitType(INamedTypeSymbol type)
        {
            var attribute = GeneratorSupport.FindAttribute(type, GeneratorSupport.NativeTypeAttribute)!;
            int policy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? GeneratorSupport.PolicyDefault;
            string adaptedName = GeneratorSupport.GetStringNamed(attribute, "Name")
                ?? GeneratorSupport.Apply(type.Name, policy, isMember: false);
            string name = type.Arity > 0 ? adaptedName + "`" + type.Arity : adaptedName;
            string? module = GeneratorSupport.GetStringNamed(attribute, "Module");
            string fullName = module is null ? name : module + ":" + name;

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated />");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("using Surtr.Runtime;");
            builder.AppendLine("using Surtr.Runtime.Classes;");
            builder.AppendLine("using Surtr.Runtime.Objects;");
            builder.AppendLine("using Surtr.Interop;");
            builder.AppendLine();

            string ns = type.ContainingNamespace.IsGlobalNamespace ? string.Empty : type.ContainingNamespace.ToDisplayString();

            if (!string.IsNullOrEmpty(ns))
            {
                builder.AppendLine("namespace " + ns);
                builder.AppendLine("{");
            }

            string indent = string.IsNullOrEmpty(ns) ? string.Empty : "    ";
            bool isPartial = type.DeclaringSyntaxReferences.Any(static r => r.GetSyntax() is TypeDeclarationSyntax { } t && t.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)));

            if (type.TypeKind == TypeKind.Enum)
            {
                EmitEnumRegistration(builder, type, attribute, name, module, fullName, indent);
            }
            else if (isPartial)
            {
                builder.AppendLine(indent + "public partial class " + type.Name);
                builder.AppendLine(indent + "{");
                EmitMembers(builder, type, policy, indent + "    ");
                builder.AppendLine(indent + "}");
            }
            else
            {
                builder.AppendLine(indent + "internal static class SurtrGenerated_" + type.Name);
                builder.AppendLine(indent + "{");
                EmitMembers(builder, type, policy, indent + "    ");
                builder.AppendLine(indent + "}");
            }

            if (!string.IsNullOrEmpty(ns))
                builder.AppendLine("}");

            return builder.ToString();
        }

        private static void EmitEnumRegistration(StringBuilder builder, INamedTypeSymbol type, AttributeData attribute, string name, string? module, string fullName, string indent)
        {
            string enumType = type.ToDisplayString();
            var fields = type.GetMembers().OfType<IFieldSymbol>().Where(static f => f.HasConstantValue).ToList();

            builder.AppendLine(indent + "internal static class SurtrGenerated_" + type.Name);
            builder.AppendLine(indent + "{");
            builder.AppendLine(indent + "    " + GeneratedCodeAttribute);
            builder.AppendLine(indent + "    internal static SurtrClass __SurtrRegister(SurtrRuntime runtime)");
            builder.AppendLine(indent + "    {");
            builder.AppendLine(indent + "        var d = new NativeTypeDescriptor");
            builder.AppendLine(indent + "        {");
            builder.AppendLine(indent + "            FullName = \"" + fullName + "\",");
            builder.AppendLine(indent + "            Name = \"" + name + "\",");
            builder.AppendLine(indent + "            Kind = NativeTypeKind.Enum,");
            builder.AppendLine(indent + "            EnumCases = new string[] { " + string.Join(", ", fields.Select(f => "\"" + f.Name + "\"")) + " },");
            builder.AppendLine(indent + "            EnumValues = new object[] { " + string.Join(", ", fields.Select(f => "(object)" + enumType + "." + f.Name)) + " },");
            builder.AppendLine(indent + "        };");
            builder.AppendLine(indent + "        return SurtrBridge.Register(runtime, d);");
            builder.AppendLine(indent + "    }");
            builder.AppendLine(indent + "}");
        }

        private static void EmitMembers(StringBuilder builder, INamedTypeSymbol type, int policy, string indent)
        {
            var methods = new List<IMethodSymbol>();
            var fields = new List<IFieldSymbol>();
            var properties = new List<IPropertySymbol>();
            var comparisons = new List<IMethodSymbol>();

            // A static factory marked [SurtrNativeConstructor] plays the constructor role for an
            // inline value type, which cannot expose instance constructors at all - its value is
            // its own result. Marked separately so the ordinary-method walk below skips them:
            // registering the same method twice would collide in the class's member tables.
            var factoryConstructors = new HashSet<IMethodSymbol>(SymbolEqualityComparer.Default);
            if (InlineLayout.IsInline(type))
            {
                foreach (var candidate in type.GetMembers().OfType<IMethodSymbol>())
                {
                    if (candidate.MethodKind == MethodKind.Ordinary
                        && candidate.IsStatic
                        && candidate.DeclaredAccessibility == Accessibility.Public
                        && candidate.Parameters.All(static p => p.RefKind == RefKind.None)
                        && ReferenceEquals(candidate.ReturnType, type)
                        && GeneratorSupport.FindAttribute(candidate, GeneratorSupport.NativeConstructorAttribute) is not null)
                    {
                        factoryConstructors.Add(candidate);
                        methods.Add(candidate);
                    }
                }
            }

            // An inline value type has no instance constructors to expose: its value is its own
            // result, and [SurtrNativeConstructor] factories above play that role. An ordinary
            // native class keeps them - they cross the wire as instance factories, no receiver.
            if (!InlineLayout.IsInline(type))
            {
                foreach (var constructor in type.InstanceConstructors.Where(static c => c.DeclaredAccessibility == Accessibility.Public && !c.IsStatic && !HasRefIn(c)))
                    methods.Add(constructor);
            }

            foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
            {
                if (factoryConstructors.Contains(method))
                    continue;

                if (IsCompareTo(method) && method.DeclaredAccessibility == Accessibility.Public)
                {
                    comparisons.Add(method);
                    continue;
                }

                if (method.MethodKind == MethodKind.Ordinary
                    && method.DeclaredAccessibility == Accessibility.Public
                    && !method.IsAbstract
                    && !HasRefIn(method)
                    && GeneratorSupport.FindAttribute(method, GeneratorSupport.NativeIgnoreAttribute) is null)
                {
                    methods.Add(method);
                }
            }

            foreach (var field in type.GetMembers().OfType<IFieldSymbol>())
            {
                if (field.DeclaredAccessibility == Accessibility.Public
                    && !field.IsConst
                    && !field.IsImplicitlyDeclared
                    && GeneratorSupport.FindAttribute(field, GeneratorSupport.NativeIgnoreAttribute) is null)
                {
                    fields.Add(field);
                }
            }

            foreach (var property in type.GetMembers().OfType<IPropertySymbol>())
            {
                if (property.DeclaredAccessibility == Accessibility.Public
                    && !property.IsIndexer
                    && GeneratorSupport.FindAttribute(property, GeneratorSupport.NativeIgnoreAttribute) is null)
                {
                    properties.Add(property);
                }
            }

            var descriptors = new List<string>();

            foreach (var method in methods)
                descriptors.Add(EmitMethod(builder, type, method, policy, indent, asConstructor: method.MethodKind == MethodKind.Constructor || factoryConstructors.Contains(method)));

            foreach (var comparison in comparisons)
                descriptors.Add(EmitComparison(builder, type, comparison, policy, indent));

            bool inline = InlineLayout.IsInline(type);

            foreach (var field in fields)
            {
                // An inline type's instance fields are its storage, so they become real slots
                // rather than accessor pairs - no shim is emitted for them at all. A static one is
                // not part of any block and keeps the ordinary native-field shape.
                if (inline && !field.IsStatic)
                {
                    descriptors.Add(EmitValueField(type, field, policy));
                    continue;
                }

                descriptors.Add(EmitField(builder, type, field, policy, indent));
            }

            foreach (var property in properties)
                descriptors.Add(EmitProperty(builder, type, property, policy, indent));

            foreach (var indexer in type.GetMembers().OfType<IPropertySymbol>().Where(static p => p.IsIndexer && p.DeclaredAccessibility == Accessibility.Public))
                descriptors.AddRange(EmitIndexer(builder, type, indexer, policy, indent));

            foreach (var op in type.GetMembers().OfType<IMethodSymbol>().Where(static m => m.MethodKind == MethodKind.UserDefinedOperator && m.DeclaredAccessibility == Accessibility.Public))
            {
                var emitted = EmitOperator(builder, type, op, policy, indent);
                if (emitted is not null)
                    descriptors.Add(emitted);
            }

            EmitRegistration(builder, type, policy, descriptors, indent);
        }

        private static string EmitMethod(StringBuilder builder, INamedTypeSymbol type, IMethodSymbol method, int policy, string indent, bool asConstructor)
        {
            var attribute = GeneratorSupport.FindAttribute(method, GeneratorSupport.NativeMethodAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = asConstructor
                ? "ctor"
                : GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(method.Name, memberPolicy, isMember: true);

            // A real constructor's shim is named after the type; a factory keeps its own name so
            // the two cannot collide when both exist on one inline type.
            string shimName = "__SurtrInvoke_" + type.Name + "_"
                + (method.MethodKind == MethodKind.Constructor ? "ctor" : method.Name) + "_" + method.Parameters.Length;
            EmitMethodShim(builder, type, method, shimName, indent, asConstructor);

            var parameters = new List<string>();
            int argIndex = method.IsStatic ? 0 : 1;
            foreach (var parameter in method.Parameters)
            {
                if (parameter.RefKind == RefKind.Out || parameter.RefKind == RefKind.Ref)
                    continue;

                string paramName = GeneratorSupport.GetStringNamed(
                    GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute),
                    "Name") ?? GeneratorSupport.Apply(parameter.Name, memberPolicy, isMember: true);

                string paramDescriptor = GeneratorSupport.GetStringNamed(
                    GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute),
                    "TypeDescriptor") ?? GeneratorSupport.MapType(parameter.Type);

                parameters.Add("new NativeParameterDescriptor { Name = \"" + paramName + "\", TypeDescriptor = \"" + paramDescriptor + "\" }");
            }

            string returnDescriptor = BuildReturnDescriptor(method, attribute, memberPolicy);

            var descriptor = new StringBuilder();
            descriptor.Append("new NativeMethodDescriptor { Name = \"" + name + "\"");
            descriptor.Append(", IsStatic = " + (method.IsStatic ? "true" : "false"));
            descriptor.Append(", IsConstructor = " + (asConstructor ? "true" : "false"));
            descriptor.Append(", IsVirtual = " + (method.IsVirtual ? "true" : "false"));
            descriptor.Append(", IsOverride = " + (method.IsOverride ? "true" : "false"));
            descriptor.Append(", ReturnDescriptor = \"" + (asConstructor
                ? // A constructor's result is the instance it creates: the return names the class,
                  // which is what makes `ArgumentSlotCount` treat it as a receiverless factory.
                  GeneratorSupport.MapType(type)
                : returnDescriptor) + "\"");
            descriptor.Append(", Parameters = new NativeParameterDescriptor[] { " + string.Join(", ", parameters) + " }");
            descriptor.Append(", EntryPoint = SurtrNativeEntryPoint.FromFunctionPointer(&" + shimName + ")");
            descriptor.Append(" }");

            return descriptor.ToString();
        }

        private static void EmitMethodShim(StringBuilder builder, INamedTypeSymbol type, IMethodSymbol method, string shimName, string indent, bool asConstructor)
        {
            string typeName = type.ToDisplayString();

            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "private static int " + shimName + "(SurtrCallArguments args)");
            builder.AppendLine(indent + "{");

            // A constructor - real or factory - has no receiver on the wire: its parameters start
            // at slot 0 and the new instance is written over that same slot.
            bool wireStatic = method.IsStatic || asConstructor;
            var receiverLayout = wireStatic ? null : InlineLayout.For(type);

            string targetExpr;
            if (wireStatic)
                targetExpr = typeName;
            else if (receiverLayout is not null)
            {
                // An inline receiver is the block in the argument slots, not a reference to
                // resolve: it is rebuilt with an object initializer, which is typed and allocates
                // nothing - the whole advantage of the generated path over the fallback.
                builder.AppendLine(indent + "    var __target = " + ReadBlock(receiverLayout, 0) + ";");
                targetExpr = "__target";
            }
            else
            {
                // A host class deriving from SurtrNativeObject is its own entity: the reference
                // resolves straight to it, and digging through a proxy's Target would reach null
                // or the wrong object. Anything else sits behind a proxy to unwrap.
                builder.AppendLine(indent + "    var __target = " + ToClrReceiver(type, 0) + ";");
                targetExpr = "__target";
            }

            var arguments = new List<string>();

            // An argument is not necessarily a slot: a parameter typed as an inline struct occupies
            // its whole block, so the walk advances by width rather than by one.
            int argIndex = wireStatic ? 0 : receiverLayout?.Width ?? 1;

            foreach (var parameter in method.Parameters)
            {
                if (parameter.RefKind == RefKind.Ref)
                    continue;

                if (parameter.RefKind == RefKind.Out)
                {
                    builder.AppendLine(indent + "    " + OutDeclaration(parameter));
                    arguments.Add("out " + parameter.Name);
                    continue;
                }

                var parameterLayout = InlineLayout.For(parameter.Type);

                if (parameterLayout is not null)
                {
                    builder.AppendLine(indent + "    var " + parameter.Name + " = " + ReadBlock(parameterLayout, argIndex) + ";");
                    arguments.Add(parameter.Name);
                    argIndex += parameterLayout.Width;
                    continue;
                }

                builder.AppendLine(indent + "    var " + parameter.Name + " = " + ToClrExpression(parameter.Type, argIndex) + ";");
                arguments.Add(parameter.Name);
                argIndex++;
            }

            bool hasOut = method.Parameters.Any(static p => p.RefKind == RefKind.Out);
            bool realConstructor = asConstructor && !method.IsStatic;

            // A factory keeps its inline result layout - the struct it returns travels as its flat
            // block, exactly what construction syntax expects to find. A real constructor's
            // "result" is the wrapped reference written by the tail below, not a block.
            var resultLayout = realConstructor ? null : InlineLayout.For(method.ReturnType);

            if (!hasOut && resultLayout is not null)
            {
                // An inline result is written as its own flat block: the declared return is a value
                // type, so `ResultSlotCount` is its width and the caller copies that many slots.
                // Computed into a local first, because the results alias the arguments and every
                // input has to be read before the first write.
                builder.AppendLine(indent + "    var __result = " + targetExpr + "." + method.Name + "(" + string.Join(", ", arguments) + ");");
                WriteBlock(builder, resultLayout, "__result", 0, indent);
                builder.AppendLine(indent + "    return " + resultLayout.Width + ";");
                builder.AppendLine(indent + "}");
                builder.AppendLine();
                return;
            }

            string returnExpr;
            if (realConstructor)
            {
                // A host class deriving from SurtrNativeObject is registered as the entity itself:
                // wrapping it would bury the object the class carries inside a shell proxy, and
                // reading it back through Target would reach null or the wrong thing.
                string construction = "new " + typeName + "(" + string.Join(", ", arguments) + ")";
                returnExpr = DerivesFromNativeObject(type)
                    ? "args.Runtime.RegisterHost(" + construction + ")"
                    : "SurtrValue.CreateReference(args.Runtime.WrapNative(" + construction + ").GetSurtrReference())";
            }
            else if (method.ReturnsVoid)
                returnExpr = "SurtrValue.Null";
            else
                returnExpr = ToSurtrExpression(method.ReturnType, targetExpr + "." + method.Name + "(" + string.Join(", ", arguments) + ")");

            if (!hasOut)
            {
                builder.AppendLine(indent + "    return args.Return(" + returnExpr + ");");
            }
            else
            {
                EmitOutReturn(builder, method, targetExpr, arguments, indent);
            }

            builder.AppendLine(indent + "}");
            builder.AppendLine();
        }

        /// <summary>
        /// An expression rebuilding an inline struct from the <paramref name="offset"/>-th slot on.
        /// </summary>
        /// <remarks>
        /// An object initializer over the public fields, so the whole read is one typed expression
        /// with no boxing and no reflection. A nested inline field expands into its own initializer
        /// at the right offset, which is what keeps a <c>Bounds</c> one flat run of six slots
        /// rather than two references.
        /// </remarks>
        private static string ReadBlock(InlineLayout layout, int offset)
        {
            var parts = new List<string>(layout.Slots.Length);
            int at = offset;

            foreach (var slot in layout.Slots)
            {
                parts.Add(slot.Field.Name + " = " + (slot.Nested is null
                    ? ToClrExpression(slot.Field.Type, at)
                    : ReadBlock(slot.Nested, at)));

                at += slot.Width;
            }

            return "new " + layout.Type.ToDisplayString() + " { " + string.Join(", ", parts) + " }";
        }

        /// <summary>
        /// Writes an inline struct held in <paramref name="source"/> into the slots from
        /// <paramref name="offset"/> on.
        /// </summary>
        private static void WriteBlock(StringBuilder builder, InlineLayout layout, string source, int offset, string indent)
        {
            int at = offset;

            foreach (var slot in layout.Slots)
            {
                if (slot.Nested is null)
                    builder.AppendLine(indent + "    args.WriteResult(" + at + ", " + ToSurtrExpression(slot.Field.Type, source + "." + slot.Field.Name) + ");");
                else
                    WriteBlock(builder, slot.Nested, source + "." + slot.Field.Name, at, indent);

                at += slot.Width;
            }
        }

        private static void EmitOutReturn(StringBuilder builder, IMethodSymbol method, string targetExpr, List<string> arguments, string indent)
        {
            string call = method.MethodKind == MethodKind.Constructor
                ? "new " + method.ContainingType.ToDisplayString() + "(" + string.Join(", ", arguments) + ")"
                : targetExpr + "." + method.Name + "(" + string.Join(", ", arguments) + ")";

            builder.AppendLine(indent + "    var __result = " + call + ";");

            var outParams = method.Parameters.Where(static p => p.RefKind == RefKind.Out).ToList();

            if (outParams.Count == 1 && method.ReturnsVoid)
            {
                builder.AppendLine(indent + "    return args.Return(" + ToSurtrExpression(outParams[0].Type, outParams[0].Name) + ");");
                return;
            }

            var elements = new List<string>();
            if (!method.ReturnsVoid)
                elements.Add(ToSurtrExpression(method.ReturnType, "__result"));
            foreach (var p in outParams)
                elements.Add(ToSurtrExpression(p.Type, p.Name));

            // Written as a flat block of slots, not as a reference to a packed SurtrTuple. A tuple
            // is a value type, so the method's `ResultSlotCount` is its flattened width and the
            // caller copies that many slots back - a single reference in slot 0 would leave the
            // rest of the block holding whatever the stack had there. Every conversion runs into a
            // local first and the writes come after, because a result aliases the arguments and
            // `WriteResult` cannot tell a stale read from a fresh one.
            for (int i = 0; i < elements.Count; i++)
                builder.AppendLine(indent + "    var __slot" + i + " = " + elements[i] + ";");

            for (int i = 0; i < elements.Count; i++)
                builder.AppendLine(indent + "    args.WriteResult(" + i + ", __slot" + i + ");");

            builder.AppendLine(indent + "    return " + elements.Count + ";");
        }

        private static string EmitField(StringBuilder builder, INamedTypeSymbol type, IFieldSymbol field, int policy, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(field, GeneratorSupport.NativeFieldAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(field.Name, memberPolicy, isMember: true);
            string typeDescriptor = GeneratorSupport.GetStringNamed(attribute, "TypeDescriptor") ?? GeneratorSupport.MapType(field.Type);
            bool readOnly = field.IsReadOnly || field.IsConst || GeneratorSupport.GetIntNamed(attribute, "ReadOnly") == 1;

            string typeName = type.ToDisplayString();
            string getterShim = "__SurtrFieldGet_" + type.Name + "_" + field.Name;
            string setterShim = "__SurtrFieldSet_" + type.Name + "_" + field.Name;

            // Getter shim.
            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "private static int " + getterShim + "(SurtrCallArguments args)");
            builder.AppendLine(indent + "{");
            string target = field.IsStatic
                ? typeName
                : ToClrReceiver(type, 0);
            if (!field.IsStatic)
                builder.AppendLine(indent + "    var __target = " + target + ";");
            builder.AppendLine(indent + "    return args.Return(" + ToSurtrExpression(field.Type, (field.IsStatic ? typeName : "__target") + "." + field.Name) + ");");
            builder.AppendLine(indent + "}");
            builder.AppendLine();

            // Setter shim (unless read-only).
            if (!readOnly)
            {
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static int " + setterShim + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                if (!field.IsStatic)
                    builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                int valueIndex = field.IsStatic ? 0 : 1;
                builder.AppendLine(indent + "    var __value = " + ToClrExpression(field.Type, valueIndex) + ";");
                builder.AppendLine(indent + "    " + (field.IsStatic ? typeName : "__target") + "." + field.Name + " = __value;");
                builder.AppendLine(indent + "    return 0;");
                builder.AppendLine(indent + "}");
                builder.AppendLine();
            }

            return "new NativeFieldDescriptor { Name = \"" + name + "\", IsStatic = " + (field.IsStatic ? "true" : "false") + ", ReadOnly = " + (readOnly ? "true" : "false") + ", TypeDescriptor = \"" + typeDescriptor + "\", Getter = SurtrNativeEntryPoint.FromFunctionPointer(&" + getterShim + "), Setter = " + (readOnly ? "default" : "SurtrNativeEntryPoint.FromFunctionPointer(&" + setterShim + ")") + " }";
        }

        /// <summary>
        /// One storage field of an inline value type. No shim: the slot <em>is</em> the storage, so
        /// reading it from Surtr never enters host code and there is nothing to dispatch to.
        /// </summary>
        private static string EmitValueField(INamedTypeSymbol type, IFieldSymbol field, int policy)
        {
            var attribute = GeneratorSupport.FindAttribute(field, GeneratorSupport.NativeFieldAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(field.Name, memberPolicy, isMember: true);
            string typeDescriptor = GeneratorSupport.GetStringNamed(attribute, "TypeDescriptor") ?? GeneratorSupport.MapType(field.Type);

            return "new NativeValueFieldDescriptor { Name = \"" + name + "\", TypeDescriptor = \"" + typeDescriptor
                   + "\", Field = typeof(" + type.ToDisplayString() + ").GetField(\"" + field.Name + "\") }";
        }

        private static string EmitProperty(StringBuilder builder, INamedTypeSymbol type, IPropertySymbol property, int policy, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(property, GeneratorSupport.NativePropertyAttribute);
            int memberPolicy = GeneratorSupport.GetIntNamed(attribute, "NamingPolicy") ?? policy;
            string name = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(property.Name, memberPolicy, isMember: true);
            string typeDescriptor = GeneratorSupport.GetStringNamed(attribute, "TypeDescriptor") ?? GeneratorSupport.MapType(property.Type);

            string typeName = type.ToDisplayString();
            bool hasGetter = property.GetMethod is { DeclaredAccessibility: Accessibility.Public };
            bool isStatic = (property.GetMethod ?? property.SetMethod)?.IsStatic ?? false;

            // A setter on an inline receiver would write to a copy that is discarded the moment the
            // shim returns, so an inline value type has no writable instance member at all. A static
            // property is not part of any block and keeps its setter.
            bool hasSetter = property.SetMethod is { DeclaredAccessibility: Accessibility.Public }
                             && (isStatic || !InlineLayout.IsInline(type));

            string getterShim = "__SurtrPropGet_" + type.Name + "_" + property.Name;
            string setterShim = "__SurtrPropSet_" + type.Name + "_" + property.Name;

            if (hasGetter)
            {
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static int " + getterShim + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                var getterReceiver = isStatic ? null : InlineLayout.For(type);
                string target = isStatic
                    ? typeName
                    : getterReceiver is not null
                        ? ReadBlock(getterReceiver, 0)
                        : ToClrReceiver(type, 0);

                if (!isStatic)
                    builder.AppendLine(indent + "    var __target = " + target + ";");

                string source = (isStatic ? typeName : "__target") + "." + property.Name;
                var getterResult = InlineLayout.For(property.Type);

                if (getterResult is not null)
                {
                    builder.AppendLine(indent + "    var __result = " + source + ";");
                    WriteBlock(builder, getterResult, "__result", 0, indent);
                    builder.AppendLine(indent + "    return " + getterResult.Width + ";");
                }
                else
                {
                    builder.AppendLine(indent + "    return args.Return(" + ToSurtrExpression(property.Type, source) + ");");
                }

                builder.AppendLine(indent + "}");
                builder.AppendLine();
            }

            if (hasSetter)
            {
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static int " + setterShim + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                if (!isStatic)
                    builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                int valueIndex = isStatic ? 0 : 1;
                builder.AppendLine(indent + "    var __value = " + ToClrExpression(property.Type, valueIndex) + ";");
                builder.AppendLine(indent + "    " + (isStatic ? typeName : "__target") + "." + property.Name + " = __value;");
                builder.AppendLine(indent + "    return 0;");
                builder.AppendLine(indent + "}");
                builder.AppendLine();
            }

            return "new NativePropertyDescriptor { Name = \"" + name + "\", IsStatic = " + (isStatic ? "true" : "false") + ", HasGetter = " + (hasGetter ? "true" : "false") + ", HasSetter = " + (hasSetter ? "true" : "false") + ", TypeDescriptor = \"" + typeDescriptor + "\", Getter = " + (hasGetter ? "SurtrNativeEntryPoint.FromFunctionPointer(&" + getterShim + ")" : "default") + ", Setter = " + (hasSetter ? "SurtrNativeEntryPoint.FromFunctionPointer(&" + setterShim + ")" : "default") + " }";
        }

        private static string? EmitOperator(StringBuilder builder, INamedTypeSymbol type, IMethodSymbol method, int policy, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(method, GeneratorSupport.NativeMethodAttribute);
            string returnDescriptor = GeneratorSupport.GetStringNamed(attribute, "ReturnDescriptor") ?? GeneratorSupport.MapType(method.ReturnType);

            string? operatorName = GeneratorSupport.MapOperator(method.Name, method.Parameters.Length, returnDescriptor);
            if (operatorName is null)
                return null; // unmapped -> a warning is reported by ReportWarnings

            string shimName = "__SurtrInvoke_" + type.Name + "_" + method.Name + "_" + method.Parameters.Length;
            string typeName = type.ToDisplayString();

            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "private static int " + shimName + "(SurtrCallArguments args)");
            builder.AppendLine(indent + "{");

            var arguments = new List<string>();
            int argIndex = 0;
            foreach (var parameter in method.Parameters)
            {
                // An operand typed as an inline struct is its whole block, so the walk advances by
                // width. `a + b` over a three-slot value is six slots in, not two.
                var operandLayout = InlineLayout.For(parameter.Type);
                if (operandLayout is not null)
                {
                    builder.AppendLine(indent + "    var " + parameter.Name + " = " + ReadBlock(operandLayout, argIndex) + ";");
                    arguments.Add(parameter.Name);
                    argIndex += operandLayout.Width;
                    continue;
                }

                builder.AppendLine(indent + "    var " + parameter.Name + " = " + ToClrExpression(parameter.Type, argIndex) + ";");
                arguments.Add(parameter.Name);
                argIndex++;
            }

            string call = OperatorExpression(method, arguments, typeName);
            var operatorResultLayout = InlineLayout.For(method.ReturnType);

            if (operatorResultLayout is not null)
            {
                builder.AppendLine(indent + "    var __result = " + call + ";");
                WriteBlock(builder, operatorResultLayout, "__result", 0, indent);
                builder.AppendLine(indent + "    return " + operatorResultLayout.Width + ";");
            }
            else
            {
                builder.AppendLine(indent + "    return args.Return(" + (method.ReturnsVoid ? "SurtrValue.Null" : ToSurtrExpression(method.ReturnType, call)) + ");");
            }

            builder.AppendLine(indent + "}");
            builder.AppendLine();

            var parameters = new List<string>();
            foreach (var parameter in method.Parameters)
            {
                string paramName = GeneratorSupport.GetStringNamed(GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute), "Name")
                    ?? GeneratorSupport.Apply(parameter.Name, policy, isMember: true);
                string paramDescriptor = GeneratorSupport.GetStringNamed(GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute), "TypeDescriptor")
                    ?? GeneratorSupport.MapType(parameter.Type);
                parameters.Add("new NativeParameterDescriptor { Name = \"" + paramName + "\", TypeDescriptor = \"" + paramDescriptor + "\" }");
            }

            return "new NativeMethodDescriptor { Name = \"" + operatorName + "\", IsStatic = true, ReturnDescriptor = \"" + returnDescriptor + "\", Parameters = new NativeParameterDescriptor[] { " + string.Join(", ", parameters) + " }, EntryPoint = SurtrNativeEntryPoint.FromFunctionPointer(&" + shimName + ") }";
        }

        private static IEnumerable<string> EmitIndexer(StringBuilder builder, INamedTypeSymbol type, IPropertySymbol indexer, int policy, string indent)
        {
            var result = new List<string>();

            if (indexer.Parameters.Length != 1)
                return result; // Surtr's operator[] is one-dimensional

            string typeName = type.ToDisplayString();
            string selfDescriptor = GeneratorSupport.MapType(type);
            string elementDescriptor = GeneratorSupport.MapType(indexer.Type);
            var indexParameter = indexer.Parameters[0];
            string indexDescriptor = GeneratorSupport.MapType(indexParameter.Type);
            string indexName = indexParameter.Name;

            if (indexer.GetMethod is { DeclaredAccessibility: Accessibility.Public })
            {
                string shimName = "__SurtrIndexGet_" + type.Name;
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static int " + shimName + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                builder.AppendLine(indent + "    var " + indexName + " = " + ToClrExpression(indexParameter.Type, 1) + ";");
                builder.AppendLine(indent + "    return args.Return(" + ToSurtrExpression(indexer.Type, "__target[" + indexName + "]") + ");");
                builder.AppendLine(indent + "}");
                builder.AppendLine();

                result.Add("new NativeMethodDescriptor { Name = \"op_[]\", IsStatic = true, ReturnDescriptor = \"" + elementDescriptor + "\", Parameters = new NativeParameterDescriptor[] { new NativeParameterDescriptor { Name = \"self\", TypeDescriptor = \"" + selfDescriptor + "\" }, new NativeParameterDescriptor { Name = \"" + indexName + "\", TypeDescriptor = \"" + indexDescriptor + "\" } }, EntryPoint = SurtrNativeEntryPoint.FromFunctionPointer(&" + shimName + ") }");
            }

            if (indexer.SetMethod is { DeclaredAccessibility: Accessibility.Public })
            {
                string shimName = "__SurtrIndexSet_" + type.Name;
                builder.AppendLine(indent + GeneratedCodeAttribute);
                builder.AppendLine(indent + "private static int " + shimName + "(SurtrCallArguments args)");
                builder.AppendLine(indent + "{");
                builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
                builder.AppendLine(indent + "    var " + indexName + " = " + ToClrExpression(indexParameter.Type, 1) + ";");
                builder.AppendLine(indent + "    var __value = " + ToClrExpression(indexer.Type, 2) + ";");
                builder.AppendLine(indent + "    __target[" + indexName + "] = __value;");
                builder.AppendLine(indent + "    return 0;");
                builder.AppendLine(indent + "}");
                builder.AppendLine();

                result.Add("new NativeMethodDescriptor { Name = \"op_[]\", IsStatic = true, ReturnDescriptor = \"V\", Parameters = new NativeParameterDescriptor[] { new NativeParameterDescriptor { Name = \"self\", TypeDescriptor = \"" + selfDescriptor + "\" }, new NativeParameterDescriptor { Name = \"" + indexName + "\", TypeDescriptor = \"" + indexDescriptor + "\" }, new NativeParameterDescriptor { Name = \"value\", TypeDescriptor = \"" + elementDescriptor + "\" } }, EntryPoint = SurtrNativeEntryPoint.FromFunctionPointer(&" + shimName + ") }");
            }

            return result;
        }

        private static string EmitComparison(StringBuilder builder, INamedTypeSymbol type, IMethodSymbol method, int policy, string indent)
        {
            string typeName = type.ToDisplayString();
            string shimName = "__SurtrComparison_" + type.Name;
            var parameter = method.Parameters[0];
            string parameterDescriptor = GeneratorSupport.MapType(parameter.Type);
            string parameterName = GeneratorSupport.Apply(parameter.Name, policy, isMember: true);

            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "private static int " + shimName + "(SurtrCallArguments args)");
            builder.AppendLine(indent + "{");
            builder.AppendLine(indent + "    var __target = args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(0))!.TargetAs<" + typeName + ">()!;");
            builder.AppendLine(indent + "    var " + parameter.Name + " = " + ToClrExpression(parameter.Type, 1) + ";");
            builder.AppendLine(indent + "    return SurtrValue.CreateInt((int)(__target.CompareTo(" + parameter.Name + ")));");
            builder.AppendLine(indent + "}");
            builder.AppendLine();

            return "new NativeMethodDescriptor { Name = \"op_<=\u003e\", IsStatic = false, ReturnDescriptor = \"I\", Parameters = new NativeParameterDescriptor[] { new NativeParameterDescriptor { Name = \"" + parameterName + "\", TypeDescriptor = \"" + parameterDescriptor + "\" } }, EntryPoint = SurtrNativeEntryPoint.FromFunctionPointer(&" + shimName + ") }";
        }

        private static bool IsCompareTo(IMethodSymbol method)
            => method.Name == "CompareTo"
               && !method.IsStatic
               && method.Parameters.Length == 1
               && method.ReturnType.SpecialType == SpecialType.System_Int32
               && ImplementsComparable(method.ContainingType);

        private static bool ImplementsComparable(INamedTypeSymbol type)
        {
            foreach (var interfaceType in type.AllInterfaces)
            {
                if (interfaceType.ToDisplayString() == "System.IComparable"
                    || (interfaceType.IsGenericType && interfaceType.OriginalDefinition.ToDisplayString() == "System.IComparable<T>"))
                {
                    return true;
                }
            }

            return false;
        }

        private static void EmitRegistration(StringBuilder builder, INamedTypeSymbol type, int policy, List<string> descriptors, string indent)
        {
            var attribute = GeneratorSupport.FindAttribute(type, GeneratorSupport.NativeTypeAttribute)!;
            string adaptedName = GeneratorSupport.GetStringNamed(attribute, "Name") ?? GeneratorSupport.Apply(type.Name, policy, isMember: false);
            string name = type.Arity > 0 ? adaptedName + "`" + type.Arity : adaptedName;
            string? module = GeneratorSupport.GetStringNamed(attribute, "Module");
            string fullName = module is null ? name : module + ":" + name;
            string kind = type.TypeKind == TypeKind.Struct ? "NativeTypeKind.Struct" : "NativeTypeKind.Class";

            builder.AppendLine(indent + GeneratedCodeAttribute);
            builder.AppendLine(indent + "internal static unsafe SurtrClass __SurtrRegister(SurtrRuntime runtime)");
            builder.AppendLine(indent + "{");
            builder.AppendLine(indent + "    var d = new NativeTypeDescriptor");
            builder.AppendLine(indent + "    {");
            builder.AppendLine(indent + "        FullName = \"" + fullName + "\",");
            builder.AppendLine(indent + "        Name = \"" + name + "\",");
            builder.AppendLine(indent + "        Kind = " + kind + ",");

            // An inline struct's storage is Surtr's, so the descriptor says so and carries the CLR
            // type the marshaler would need if anything ever fell back to reflection for it.
            if (InlineLayout.IsInline(type))
            {
                builder.AppendLine(indent + "        IsInline = true,");
                builder.AppendLine(indent + "        ClrType = typeof(" + type.ToDisplayString() + "),");
            }

            if (type.Arity > 0)
                builder.AppendLine(indent + "        TypeArguments = new string[] { " + string.Join(", ", type.TypeArguments.Select(static a => "\"" + GeneratorSupport.MapType(a) + "\"")) + " },");

            builder.AppendLine(indent + "        Members = new NativeMemberDescriptor[] { " + string.Join(", ", descriptors) + " },");
            builder.AppendLine(indent + "    };");
            builder.AppendLine(indent + "    return SurtrBridge.Register(runtime, d);");
            builder.AppendLine(indent + "}");
        }

        private static string RegistrationAccessor(INamedTypeSymbol type)
        {
            bool isPartial = type.DeclaringSyntaxReferences.Any(static r => r.GetSyntax() is TypeDeclarationSyntax { } t && t.Modifiers.Any(static m => m.IsKind(SyntaxKind.PartialKeyword)));
            if (type.TypeKind == TypeKind.Enum || !isPartial)
                return "global::" + type.ContainingNamespace.ToDisplayString() + ".SurtrGenerated_" + type.Name;
            return "global::" + type.ToDisplayString();
        }

        private static string BuildReturnDescriptor(IMethodSymbol method, AttributeData? attribute, int policy)
        {
            var outParams = method.Parameters.Where(static p => p.RefKind == RefKind.Out).ToList();
            string declared = GeneratorSupport.GetStringNamed(attribute, "ReturnDescriptor") ?? string.Empty;

            if (outParams.Count == 0)
                return declared.Length > 0 ? declared : GeneratorSupport.MapType(method.ReturnType);

            string? returnRef = method.ReturnsVoid ? null : (declared.Length > 0 ? declared : GeneratorSupport.MapType(method.ReturnType));

            if (outParams.Count == 1 && method.ReturnsVoid)
                return GeneratorSupport.MapType(outParams[0].Type);

            var elements = new List<string>();
            if (returnRef is not null)
                elements.Add(returnRef);
            foreach (var p in outParams)
                elements.Add(GeneratorSupport.MapType(p.Type));

            return "T(" + string.Join("", elements) + ")";
        }

        private static string OutDeclaration(IParameterSymbol parameter)
            => parameter.Type.ToDisplayString() + " " + parameter.Name + ";";

        private static string ToClrExpression(ITypeSymbol type, int index)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_SByte: return "(sbyte)args.GetInt(" + index + ")";
                case SpecialType.System_Byte: return "(byte)args.GetInt(" + index + ")";
                case SpecialType.System_Int16: return "(short)args.GetInt(" + index + ")";
                case SpecialType.System_UInt16: return "(ushort)args.GetInt(" + index + ")";
                case SpecialType.System_Int32: return "args.GetInt(" + index + ")";
                case SpecialType.System_UInt32: return "(uint)args.GetInt(" + index + ")";
                case SpecialType.System_Int64: return "args.GetInt(" + index + ")";
                case SpecialType.System_UInt64: return "(ulong)args.GetInt(" + index + ")";
                case SpecialType.System_Single: return "(float)args.GetFloat(" + index + ")";
                case SpecialType.System_Double: return "args.GetFloat(" + index + ")";
                case SpecialType.System_Decimal: return "(decimal)args.GetFloat(" + index + ")";
                case SpecialType.System_Boolean: return "args.GetBool(" + index + ")";
                case SpecialType.System_Char: return "args.GetChar(" + index + ")";
                case SpecialType.System_String: return "args.GetString(" + index + ").Text";
                case SpecialType.System_Object:
                    // The static type says nothing about which shape crossed, so the runtime
                    // decides: a proxy unwraps to its target, an adopted native object is the
                    // host object itself.
                    return "args.Runtime.HostValueOf(args.GetValue(" + index + "))";
            }

            if (type.TypeKind == TypeKind.Enum)
                return "SurtrEnums.ToClr<" + type.ToDisplayString() + ">(args.Runtime, args.GetValue(" + index + "))";

            if (type.TypeKind == TypeKind.Delegate)
                return "(" + type.ToDisplayString() + ")SurtrDelegateMarshal.ToClr(args.Runtime, args.GetValue(" + index + "), typeof(" + type.ToDisplayString() + "))";

            if (DerivesFromNativeObject(type))
                return "args.Runtime.Resolve<" + type.ToDisplayString() + ">(args.GetValue(" + index + "))!";

            return "args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(" + index + "))!.TargetAs<" + type.ToDisplayString() + ">()!";
        }

        /// <summary>
        /// The expression reading the receiver of <paramref name="type"/> from slot
        /// <paramref name="index"/>: the entity itself when the CLR class derives from
        /// <see cref="Surtr.Runtime.Objects.SurtrNativeObject"/>, its proxy's target otherwise.
        /// </summary>
        private static string ToClrReceiver(INamedTypeSymbol type, int index)
            => DerivesFromNativeObject(type)
                ? "args.Runtime.Resolve<" + type.ToDisplayString() + ">(args.GetValue(" + index + "))!"
                : "args.Runtime.Resolve<SurtrNativeObject>(args.GetValue(" + index + "))!.TargetAs<" + type.ToDisplayString() + ">()";

        /// <summary>
        /// Whether <paramref name="type"/>, or any base of it, is the runtime's
        /// <c>SurtrNativeObject</c> - the mark of a host class that is already a Surtr entity and
        /// so needs no proxy wrapped around it and none unwrapped off it.
        /// </summary>
        private static bool DerivesFromNativeObject(ITypeSymbol? type)
        {
            for (var walk = type; walk is not null; walk = walk.BaseType)
            {
                if (walk.ToDisplayString() == NativeObjectTypeName)
                    return true;
            }

            return false;
        }

        private const string NativeObjectTypeName = "Surtr.Runtime.Objects.SurtrNativeObject";

        private static string ToSurtrExpression(ITypeSymbol type, string expression)
        {
            switch (type.SpecialType)
            {
                case SpecialType.System_SByte:
                case SpecialType.System_Byte:
                case SpecialType.System_Int16:
                case SpecialType.System_UInt16:
                case SpecialType.System_Int32:
                case SpecialType.System_UInt32:
                case SpecialType.System_Int64:
                case SpecialType.System_UInt64:
                    return "SurtrValue.CreateInt((int)(" + expression + "))";

                case SpecialType.System_Single:
                case SpecialType.System_Double:
                case SpecialType.System_Decimal:
                    return "SurtrValue.CreateFloat((double)(" + expression + "))";

                case SpecialType.System_Boolean:
                    return "SurtrValue.CreateBool(" + expression + ")";

                case SpecialType.System_Char:
                    return "SurtrValue.CreateChar(" + expression + ")";

                case SpecialType.System_String:
                    return "SurtrValue.CreateReference(args.Runtime.InternString(" + expression + ").GetSurtrReference())";

                case SpecialType.System_Object:
                    // The static type says nothing about which shape will cross, so the runtime
                    // adopts what already is an entity and wraps everything else.
                    return "args.Runtime.RegisterHost(" + expression + ")";
            }

            if (type.TypeKind == TypeKind.Enum)
                return "SurtrEnums.ToSurtr(args.Runtime, " + expression + ")";

            if (type.TypeKind == TypeKind.Delegate)
                return "SurtrDelegateMarshal.ToSurtr(args.Runtime, " + expression + ", SurtrClassReference.FromDescriptor(\"" + GeneratorSupport.MapType(type) + "\"))";

            if (DerivesFromNativeObject(type))
                return "args.Runtime.RegisterHost(" + expression + ")";

            return "SurtrValue.CreateReference(args.Runtime.WrapNative(" + expression + ").GetSurtrReference())";
        }

        private static bool IsExposeFalse(AttributeData attribute)
        {
            foreach (var pair in attribute.NamedArguments)
            {
                if (pair.Key == "Expose" && pair.Value.Value is false)
                    return true;
            }

            return false;
        }

        /// <summary>Reports warnings for members the generator deliberately leaves out.</summary>
        /// <summary>Reports errors for genuinely invalid registrations: static types, arity mismatches, and malformed descriptors.</summary>
        private static void ValidateType(GeneratorExecutionContext context, INamedTypeSymbol type)
        {
            string container = type.ContainingNamespace.ToDisplayString();
            var location = type.Locations.FirstOrDefault();

            if (type.IsStatic)
            {
                context.ReportDiagnostic(Diagnostic.Create(SurtrDiagnostics.StaticType, location, type.Name));
                return;
            }

            var attribute = GeneratorSupport.FindAttribute(type, GeneratorSupport.NativeTypeAttribute);
            if (attribute is not null && type.IsGenericType)
            {
                var typeArguments = ReadTypeArguments(attribute);
                if (typeArguments.Count > 0 && typeArguments.Count != type.Arity)
                    context.ReportDiagnostic(Diagnostic.Create(SurtrDiagnostics.ArityMismatch, location, type.Name, typeArguments.Count, type.Arity));
            }

            foreach (var member in type.GetMembers())
            {
                var attributeString = GeneratorSupport.GetStringNamed(
                    GeneratorSupport.FindAttribute(member, GeneratorSupport.NativeMethodAttribute),
                    "ReturnDescriptor")
                    ?? GeneratorSupport.GetStringNamed(GeneratorSupport.FindAttribute(member, GeneratorSupport.NativeFieldAttribute), "TypeDescriptor")
                    ?? GeneratorSupport.GetStringNamed(GeneratorSupport.FindAttribute(member, GeneratorSupport.NativePropertyAttribute), "TypeDescriptor");

                if (attributeString is not null && !GeneratorSupport.IsWellFormedDescriptor(attributeString))
                    context.ReportDiagnostic(Diagnostic.Create(SurtrDiagnostics.InvalidDescriptor, member.Locations.FirstOrDefault(), member.Name, container, attributeString));

                if (member is IMethodSymbol method)
                {
                    foreach (var parameter in method.Parameters)
                    {
                        var parameterDescriptor = GeneratorSupport.GetStringNamed(
                            GeneratorSupport.FindAttribute(parameter, GeneratorSupport.NativeParameterAttribute),
                            "TypeDescriptor");

                        if (parameterDescriptor is not null && !GeneratorSupport.IsWellFormedDescriptor(parameterDescriptor))
                            context.ReportDiagnostic(Diagnostic.Create(SurtrDiagnostics.InvalidDescriptor, parameter.Locations.FirstOrDefault(), method.Name, container, parameterDescriptor));
                    }
                }
            }
        }

        private static List<ITypeSymbol> ReadTypeArguments(AttributeData attribute)
        {
            var typeArguments = new List<ITypeSymbol>();

            foreach (var pair in attribute.NamedArguments)
            {
                if (pair.Key != "TypeArguments" || pair.Value.Kind != TypedConstantKind.Array)
                    continue;

                foreach (var value in pair.Value.Values)
                {
                    if (value.Value is ITypeSymbol argument)
                        typeArguments.Add(argument);
                }
            }

            return typeArguments;
        }

        private static void ReportWarnings(GeneratorExecutionContext context, INamedTypeSymbol type)
        {
            string container = type.ContainingNamespace.ToDisplayString();

            foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
            {
                if (method.DeclaredAccessibility != Accessibility.Public)
                    continue;

                if (method.MethodKind == MethodKind.UserDefinedOperator
                    && GeneratorSupport.MapOperator(method.Name, method.Parameters.Length, GeneratorSupport.MapType(method.ReturnType)) is null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        SurtrDiagnostics.UnsupportedMember,
                        method.Locations.FirstOrDefault(),
                        method.Name,
                        container,
                        "no Surtr operator has an equivalent"));
                }

                if (method.MethodKind is MethodKind.Ordinary or MethodKind.Constructor && HasRefIn(method))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        SurtrDiagnostics.UnsupportedMember,
                        method.Locations.FirstOrDefault(),
                        method.Name,
                        container,
                        "ref/in parameters have no Surtr equivalent"));
                }

                if (method.IsAbstract)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        SurtrDiagnostics.UnsupportedMember,
                        method.Locations.FirstOrDefault(),
                        method.Name,
                        container,
                        "abstract methods have no host body to expose"));
                }
            }

            foreach (var indexer in type.GetMembers().OfType<IPropertySymbol>())
            {
                if (indexer.IsIndexer && indexer.Parameters.Length != 1)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        SurtrDiagnostics.UnsupportedMember,
                        indexer.Locations.FirstOrDefault(),
                        indexer.Name,
                        container,
                        "multi-dimensional indexers have no Surtr operator[] equivalent"));
                }
            }
        }

        /// <summary>
        /// Renders the C# expression a user-defined operator evaluates to, since an operator method
        /// cannot be called by its CLR name in source.
        /// </summary>
        private static string OperatorExpression(IMethodSymbol method, List<string> arguments, string typeName)
        {
            string binary = "(" + arguments[0] + " " + OperatorToken(method.Name) + " " + arguments[1] + ")";
            string unary = "(" + OperatorToken(method.Name) + arguments[0] + ")";

            switch (method.Name)
            {
                case "op_Explicit":
                    return "(" + method.ReturnType.ToDisplayString() + ")(" + arguments[0] + ")";

                case "op_UnaryNegation":
                case "op_LogicalNot":
                case "op_OnesComplement":
                case "op_Increment":
                case "op_Decrement":
                    return unary;

                default:
                    return binary;
            }
        }

        private static string OperatorToken(string csharpName) => csharpName switch
        {
            "op_Addition" => "+",
            "op_Subtraction" => "-",
            "op_Multiply" => "*",
            "op_Division" => "/",
            "op_Modulus" => "%",
            "op_BitwiseAnd" => "&",
            "op_BitwiseOr" => "|",
            "op_ExclusiveOr" => "^",
            "op_LeftShift" => "<<",
            "op_RightShift" => ">>",
            "op_UnsignedRightShift" => ">>>",
            "op_UnaryNegation" => "-",
            "op_LogicalNot" => "!",
            "op_OnesComplement" => "~",
            "op_Increment" => "++",
            "op_Decrement" => "--",
            "op_Equality" => "==",
            _ => "+",
        };

        private static bool HasRefIn(IMethodSymbol method)
            => method.Parameters.Any(static p => p.RefKind == RefKind.Ref || p.RefKind == RefKind.In);

        private static string Sanitize(string name)
        {
            var builder = new StringBuilder(name.Length);
            foreach (char c in name)
                builder.Append(char.IsLetterOrDigit(c) ? c : '_');
            return builder.ToString();
        }

        private sealed class SurtrSyntaxReceiver : ISyntaxReceiver
        {
            internal readonly List<TypeDeclarationSyntax> Candidates = new();

            public void OnVisitSyntaxNode(SyntaxNode syntaxNode)
            {
                if (syntaxNode is TypeDeclarationSyntax { AttributeLists.Count: > 0 } type)
                    Candidates.Add(type);
            }
        }
    }
}


